CREATE USER C##NADINE IDENTIFIED BY nadine123 CONTAINER=ALL;
GRANT CREATE SESSION, CREATE TABLE TO C##NADINE;
GRANT SELECT, INSERT ON Employees TO C##NADINE;

CREATE USER C##CHRIS IDENTIFIED BY chris123 CONTAINER=ALL;
GRANT CREATE SESSION TO C##CHRIS CONTAINER=ALL;
GRANT CREATE TABLE TO C##CHRIS CONTAINER=ALL;

CREATE USER C##AYA IDENTIFIED BY Cashier01 CONTAINER=ALL;

CREATE USER C##RINA IDENTIFIED BY HR01 CONTAINER=ALL;

CREATE USER C##LEO IDENTIFIED BY Waiter01 CONTAINER=ALL;

CREATE USER C##SAKURA IDENTIFIED BY Inventory01 CONTAINER=ALL;