CREATE PROFILE limit_login
LIMIT FAILED_LOGIN_ATTEMPTS 3;

ALTER USER C##NADINE PROFILE limit_login;
ALTER USER C##CHRIS PROFILE limit_login;
ALTER USER C##AYA PROFILE limit_login;
ALTER USER C##RINA PROFILE limit_login;
ALTER USER C##LEO PROFILE limit_login;
ALTER USER C##SAKURA PROFILE limit_login;