-- in the root
CREATE USER C##NADINE IDENTIFIED BY nadine123 CONTAINER=ALL;
CREATE USER C##CHRIS IDENTIFIED BY chris123 CONTAINER=ALL
CREATE USER C##SAKURA IDENTIFIED BY Inventory01 CONTAINER=ALL;
CREATE USER C##AYA IDENTIFIED BY Cashier01 CONTAINER=ALL;
CREATE USER C##RINA IDENTIFIED BY HR01 CONTAINER=ALL;
CREATE USER C##LEO IDENTIFIED BY Waiter01 CONTAINER=ALL;

GRANT CREATE SESSION TO C##NADINE CONTAINER=ALL;
GRANT CREATE SESSION TO C##CHRIS CONTAINER=ALL;
GRANT CREATE SESSION TO C##AYA CONTAINER=ALL;
GRANT CREATE SESSION TO C##LEO CONTAINER=ALL;
GRANT CREATE SESSION TO C##SAKURA CONTAINER=ALL;
GRANT CREATE SESSION TO C##RINA CONTAINER=ALL;

GRANT CREATE TABLE TO C##NADINE CONTAINER=ALL;
GRANT CREATE VIEW TO C##NADINE CONTAINER=ALL;
GRANT CREATE SEQUENCE TO C##NADINE CONTAINER=ALL;
GRANT CREATE PROCEDURE TO C##NADINE CONTAINER=ALL;
GRANT ALTER SESSION TO C##NADINE CONTAINER=ALL;
GRANT UNLIMITED TABLESPACE TO C##NADINE CONTAINER=ALL;

GRANT CREATE VIEW TO C##CHRIS CONTAINER=ALL;

