-- in the root
CREATE ROLE C##POS_CASHIER CONTAINER=ALL;
CREATE ROLE C##POS_MANAGER CONTAINER=ALL;
CREATE ROLE C##POS_ASSISTANTMANAGER CONTAINER=ALL;
CREATE ROLE C##POS_HR CONTAINER=ALL;
CREATE ROLE C##POS_INVENTORY CONTAINER=ALL;
CREATE ROLE C##POS_WAITER CONTAINER=ALL;
 
-- in the plugeable
GRANT SELECT, INSERT, UPDATE ON Sales TO C##POS_CASHIER;
GRANT SELECT, INSERT ON SaleItems TO C##POS_CASHIER;
GRANT SELECT, INSERT ON Payments TO C##POS_CASHIER;
GRANT SELECT ON Products TO C##POS_CASHIER;
-- in the root
    GRANT C##POS_CASHIER TO C##AYA;

-- in the plugeable
GRANT DBA TO C##POS_MANAGER;
-- in the root
GRANT C##POS_MANAGER TO C##NADINE;

-- in the plugeable
GRANT SELECT, INSERT, UPDATE ON Employees TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Customers TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Products TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Categories TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Sales TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON SaleItems TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Payments TO C##POS_ASSISTANTMANAGER;
-- in the root
GRANT C##POS_ASSISTANTMANAGER TO C##CHRIS;

-- in the plugeable
GRANT SELECT, INSERT, UPDATE ON Employees TO C##POS_HR;
-- in the root
GRANT C##POS_HR TO C##RINA;

-- in the plugeable
GRANT SELECT, INSERT, UPDATE ON Products TO C##POS_INVENTORY;
GRANT SELECT, INSERT, UPDATE ON Categories TO C##POS_INVENTORY;
-- in the root
GRANT C##POS_INVENTORY TO C##SAKURA;

-- in the plugeable
GRANT SELECT ON Products TO C##POS_WAITER;
GRANT SELECT, INSERT ON Sales TO C##POS_WAITER;
-- in the root
GRANT C##POS_WAITER TO C##LEO;