CREATE ROLE C##POS_CASHIER CONTAINER=ALL;
CREATE ROLE C##POS_MANAGER CONTAINER=ALL;
CREATE ROLE C##POS_ASSISTANTMANAGER CONTAINER=ALL;
CREATE ROLE C##POS_HR CONTAINER=ALL;
CREATE ROLE C##POS_INVENTORY CONTAINER=ALL;
CREATE ROLE C##POS_WAITER CONTAINER=ALL;


GRANT SELECT, INSERT, UPDATE ON Sales TO C##POS_CASHIER;
GRANT SELECT, INSERT ON SaleItems TO C##POS_CASHIER;
GRANT SELECT, INSERT ON Payments TO C##POS_CASHIER;
GRANT SELECT ON Products TO C##POS_CASHIER;
GRANT C##POS_CASHIER TO C##AYA;


GRANT DBA TO C##POS_MANAGER;
GRANT C##POS_MANAGER TO C##NADINE;
ALTER USER C##NADINE DEFAULT ROLE C##POS_MANAGER;


GRANT SELECT, INSERT, UPDATE ON Employees TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Customers TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Products TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Categories TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Sales TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON SaleItems TO C##POS_ASSISTANTMANAGER;
GRANT SELECT, INSERT, UPDATE ON Payments TO C##POS_ASSISTANTMANAGER;
GRANT C##POS_ASSISTANTMANAGER TO C##CHRIS;
ALTER USER C##CHRIS DEFAULT ROLE C##POS_ASSISTANTMANAGER;


GRANT SELECT, INSERT, UPDATE ON Employees TO C##POS_HR;
GRANT C##POS_HR TO C##RINA;


GRANT SELECT, INSERT, UPDATE ON Products TO C##POS_INVENTORY;
GRANT SELECT, INSERT, UPDATE ON Categories TO C##POS_INVENTORY;
GRANT C##POS_INVENTORY TO C##SAKURA;


GRANT SELECT ON Products TO C##POS_WAITER;
GRANT SELECT, INSERT ON Sales TO C##POS_WAITER;
GRANT C##POS_WAITER TO C##LEO;